USE sakila;

-- 1. List the number of films per category.
SELECT 
COUNT(f.film_id) AS number_of_films,
c.name
FROM film AS f
LEFT JOIN film_category as fc
ON fc.film_id = f.film_id
LEFT JOIN category AS c
ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY number_of_films DESC;

-- 2. Retrieve the store ID, city, and country for each store.

SELECT 
s.store_id, 
c.city, 
co.country
FROM store AS s
LEFT JOIN address AS a
ON s.address_id = a.address_id
LEFT JOIN city AS c
ON a.city_id = c.city_id
LEFT JOIN country AS co
ON c.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.

SELECT 
store_id,
SUM(p.amount) AS total_revenue
FROM payment AS p
LEFT JOIN staff AS s
ON p.staff_id = s.staff_id
GROUP BY store_id;

-- 4. Determine the average running time of films for each category.
SELECT 
c.name AS name_category, 
AVG(f.length) AS avg_length
FROM film AS f
INNER JOIN film_category AS fc
ON f.film_id = fc.film_id
INNER JOIN category AS c
ON fc.category_id = c.category_id
GROUP BY c.name;


-- 5. Identify the film categories with the longest average running time.

SELECT 
c.name AS name_category, 
AVG(f.length) AS avg_length
FROM film AS f
INNER JOIN film_category AS fc
ON f.film_id = fc.film_id
INNER JOIN category AS c
ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY avg_length DESC
LIMIT 1;

-- 6. Display the top 10 most frequently rented movies in descending order.

SELECT 
f.title, 
COUNT(r.rental_id) AS rental_count
FROM rental AS r
INNER JOIN inventory AS i
ON r.inventory_id = i.inventory_id
INNER JOIN film AS f
ON i.film_id = f.film_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT
f.title, 
i.store_id
FROM film AS f
INNER JOIN inventory AS i 
ON f.film_id = i.film_id
WHERE f.title = 'Academy Dinosaur' AND store_id = 1;

-- 8.Provide a list of all distinct film titles, along with their availability status in 
-- the inventory. Include a column indicating whether each title is 'Available' or 
-- 'NOT available.' Note that there are 42 titles that are not in the inventory, 
-- and this information can be obtained using a CASE statement combined with IFNULL."

SELECT 
f.title, 
CASE
	WHEN IFNULL(i.inventory_id, 0) = 0 THEN 'NOT available'
    ELSE 'Available'
END AS availabiliy
FROM film AS f
LEFT JOIN inventory AS i
ON f.film_id = i.film_id;







